### ISSUE TITLE
Sms read 

### ISSUE THREAD

**Issue by itsatifsiddiqui** [AppleEducate/plugins#14] opened 2019-02-23 08:57 UTC
Please add in the feature to change the isread status to true upon sone action on the message.

**Comment by AppleEducate** [comment] 2019-02-27 19:20
I am open to pull requests if you want to implement it quickly

**Comment by itsatifsiddiqui** [comment] 2019-02-27 19:23
No, i don't want to. It would be appreciated, if you implement ...

**Comment by AppleEducate** [comment] 2019-03-13 16:42
I'm closing this for now as there could be privacy issues on ios

**Closed by AppleEducate** 2019-03-13 16:42 UTC
Labels: enhancement, help wanted

**Comment by NTMS2017** [comment] 2019-04-04 12:51
I have a MacBook Pro, how can I help? But I don't know about Xcode coding. I can help if you can help me to run the issues on Mac so your plugin it can work both android and iOS, thanks

**Comment by AppleEducate** [comment] 2019-04-04 12:56
The issue is not the plug-in but Apple. There is no API Apple provides to allow reading of SMS.

**Comment by NTMS2017** [comment] 2019-04-04 13:17
I see, can I read sms on Android or its same as Apple?

**Comment by AppleEducate** [comment] 2019-04-04 17:51
Google is also cutting down on that and rejecting apps that do.

**Comment by NTMS2017** [comment] 2019-04-05 04:05
Thanks
